version: '3'
services:
    rabbitmq:
        image: rabbitmq:latest
        container_name: rabbitmq
        ports:
            - "15672:15672" # RabbitMQ Management UI port
            - "5672:5672"   # RabbitMQ default port for AMQP
        command: >
            sh -c "rabbitmq-plugins enable rabbitmq_management && rabbitmq-server"
        networks:
            - rabbitmq-network

networks:
    rabbitmq-network:
        driver: bridge
