spring:
    h2:
        console:
            enabled: true
            path: /h2
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:test
        username: sa
        password:
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        show-sql: true
    cloud:
        discovery:
          client:
            simple:
                instances:
                    community:
                        - service-id: community
                          instance-id: community1
                          uri: http://localhost:8080
        openfeign:
            okhttp:
                enabled: true

schedule:
    sales-sync:
        use: true
        cron: 0 0 8 * * ?
